//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Tractor.rc
//
#define IDS_STRING1                     1
#define IDCANCEL2                       3
#define IDD_FRONT                       101
#define IDD_FRONT_END                   101
#define IDR_MENU1                       102
#define IDD_VID_OPTIONS                 103
#define IDD_SET_TC                      104
#define IDD_ADD_ISLAND                  105
#define IDB_BITMAP1                     106
#define IDB_FRONTEND                    106
#define IDD_ABOUT                       110
#define IDB_BITMAP2                     113
#define IDD_KEYBOARD                    114
#define IDD_CHAT                        116
#define IDD_REFRESH_SERVERS             117
#define IDD_AUDIO_OPTIONS               118
#define IDD_GENERAL_OPTIONS             118
#define IDI_ICON1                       119
#define IDD_NAME_AND_PASS               120
#define IDD_SMALL                       121
#define IDR_SMALL_MENU                  122
#define IDB_BITMAP4                     129
#define IDB_BITMAP3                     130
#define IDB_BITMAP5                     131
#define IDB_BITMAP6                     132
#define IDD_AUDIO_SOURCE                133
#define IDB_BITMAP7                     137
#define IDB_LOGIN_LOGO                  137
#define IDD_INITIALISATION_POPUP        138
#define IDB_STOP_ACTIVE                 140
#define IDB_AUDIO_FOLDER                141
#define IDB_FORWARD_ACTIVE              142
#define IDB_FORWARD_INACTIVE            143
#define IDB_PLAY_ACTIVE                 144
#define IDB_PLAY_INACTIVE               145
#define IDB_REWIND_ACTIVE               146
#define IDB_REWIND_INACTIVE             147
#define IDB_STOP_INACTIVE               148
#define IDB_CDPLAYER                    149
#define IDD_FRONTEND                    150
#define IDR_SMALL_ACCELERATOR           151
#define IDI_ICON2                       156
#define IDI_ICON3                       160
#define IDD_WORLD_CONNECT               161
#define IDD_GRAPHIC_OPTIONS             162
#define IDD_CHANGE_NAME                 163
#define IDD_SERVER_PASSWORD             164
#define IDB_BITMAP8                     166
#define IDD_VIEW_ALL_ISLANDS            167
#define IDB_TREE_WORLD                  168
#define IDB_TREE_ISLAND                 170
#define IDD_CONNECTING_TO_WORLD         184
#define IDD_WORLD_DIRECTIONS            185
#define IDD_FAILED_INIT                 186
#define IDD_JOYSTICK                    187
#define IDD_ALT_GALAXY_DIALOG           190
#define IDR_MENU2                       191
#define IDD_ADD_GALAXY                  192
#define IDB_BITMAP9                     195
#define IDD_SOUND_OPTIONS               196
#define IDB_BITMAP10                    197
#define IDD_SET_PROFILE                 198
#define IDD_BAD_PASSWORD                199
#define IDB_BITMAP11                    201
#define IDD_AUTOUPDATER                 202
#define IDD_GENTEXCREATE_DIALOG         203
#define IDD_FIRST_INIT_DIALOG           204
#define IDB_BITMAP12                    205
#define IDC_FLIP_MODE_1                 999
#define IDC_DEVICE_COMBO                1000
#define IDC_FLIP_MODE_2                 1001
#define IDC_FLIP_MODE_3                 1002
#define IDC_ADAPTER_COMBO               1003
#define IDC_TEXTURE_FILTERING           1004
#define IDC_FRAME_BUFFER                1005
#define IDC_VSYNC                       1006
#define IDC_RADIO1                      1007
#define IDC_MULTITEXTURING              1007
#define IDC_JOIN_RANDOM_PRIMARY         1007
#define IDC_MINIMUM_SURFACE_RES         1008
#define IDC_MULTIPASS                   1008
#define IDC_JOIN_RANDOM                 1008
#define IDC_RADIO2                      1008
#define IDC_REFRESH_LIST                1009
#define IDC_MULTITEXTURING_OFF          1009
#define IDC_JOIN_LAST                   1009
#define IDC_RADIO3                      1009
#define IDC_SERVER_LIST                 1010
#define IDC_FILTERING_OFF               1010
#define IDC_JOIN_LOCAL                  1010
#define IDC_RADIO6                      1010
#define IDC_FULLSCREENMODES_COMBO       1011
#define IDC_FILTERING_ON                1011
#define IDC_JOIN_NAMED                  1011
#define IDC_RADIO7                      1011
#define IDC_ADD_ISLAND                  1012
#define IDC_RADIO8                      1012
#define IDC_RADIO13                     1012
#define IDC_PASS                        1013
#define IDC_RADIO9                      1013
#define IDC_RADIO14                     1013
#define IDC_EXIT_BUTTON                 1014
#define IDC_RADIO12                     1014
#define IDC_NAME                        1015
#define IDC_RADIO10                     1015
#define IDC_TC_ADDY                     1016
#define IDC_GATEWAY_IP                  1016
#define IDC_RADIO11                     1016
#define IDC_IP_ADDY                     1017
#define IDC_GATEWAY_PORT                1017
#define IDC_RADIO15                     1017
#define IDC_REMOVE_ISLAND               1018
#define IDC_RADIO16                     1018
#define IDC_PORT                        1019
#define IDC_ADD_ISLAND_MANUAL           1019
#define IDC_STARTUP_OLD                 1020
#define IDC_REMOVE_ALL_ISLANDS          1020
#define IDC_SERVER_NAME                 1021
#define IDC_MOVE_UP                     1021
#define IDC_STARTUP_OLD2                1022
#define IDC_ADVANCED                    1022
#define IDC_MOVE_DOWN                   1022
#define IDC_RADIO4                      1023
#define IDC_RADIO5                      1024
#define IDC_FULLSCREEN                  1025
#define IDC_WINDOW                      1026
#define IDC_ISLAND_INFO                 1027
#define IDC_VERSION_STRING              1035
#define IDC_JOIN                        1038
#define IDC_CURRENT_TC                  1039
#define IDC_FOG_MODE                    1040
#define IDC_CHAT_WINDOW                 1041
#define IDC_PLAYER_LIST                 1042
#define IDC_EDIT_LINE                   1044
#define IDC_TC_SERVER_LIST              1045
#define IDC_LOCAL_LIST                  1047
#define IDC_UPDATE_TC_LIST              1049
#define IDC_SOUND_CHECK                 1050
#define IDC_ENGINE_NOISE                1051
#define IDC_ENVIRONMENTAL               1052
#define IDC_CHAR_NAME                   1052
#define IDC_ENGINE_NOISE2               1052
#define IDC_SPACEFRONTVIEW              1052
#define IDC_SOUND_EFFECTS               1052
#define IDC_CHAR_PASS                   1053
#define IDC_MODEL_CHECK                 1053
#define IDC_ENGINE_NOISE3               1053
#define IDC_ALLOW_VOICE_COMMS           1053
#define IDC_CHAR_PASS2                  1054
#define IDC_EDIT1                       1054
#define IDC_START_SMALL                 1054
#define IDC_ENGINE_NOISE4               1054
#define IDC_INTRO_RADIO_CHECK           1054
#define IDC_CHAT_BACKGROUND             1055
#define IDC_UPDATE_GAME_MINUTES         1055
#define IDC_PLAYER_LOGIN                1055
#define IDC_USERNAME                    1055
#define IDC_EDIT2                       1055
#define IDC_ENGINE_NOISE5               1055
#define IDC_MESSAGE_ALERTS              1055
#define IDC_STATUS                      1056
#define IDC_START_SMALL3                1056
#define IDC_PLAYER_PASS                 1056
#define IDC_OPAQUE_WINDOWS              1056
#define IDC_EDIT3                       1056
#define IDC_EMAIL_ADDRESS               1056
#define IDC_INTRO_RADIO_LEAVEON_CHECK   1056
#define IDC_STATUS2                     1057
#define IDC_SEMI_INTERIOR               1057
#define IDC_PLAYER_PASS2                1057
#define IDC_EDIT4                       1057
#define IDC_STATUS3                     1058
#define IDC_OPAQUE_SEA                  1058
#define IDC_PLAYER_NICK                 1058
#define IDC_CHAT_BACKGROUND2            1058
#define IDC_AUTO_UPDATE_ADDRESSES       1058
#define IDC_STATUS4                     1059
#define IDC_LOAD_ANIM_ASYNC             1059
#define IDC_CHAT_BACKGROUND3            1059
#define IDC_AUTO_ADD_ISLANDS            1059
#define IDC_STATUS5                     1060
#define IDC_HIDE_PLAYERS                1060
#define IDC_STATUS8                     1061
#define IDC_ANISTROPIC                  1061
#define IDC_AUDIO_FORWARD               1062
#define IDC_32BIT_TEXTURES              1062
#define IDC_AUDIO_REWIND                1063
#define IDC_MULTIPASS_OFF               1063
#define IDC_SHIFT_CTRL                  1064
#define IDC_AUDIO_PLAY                  1064
#define IDC_DISABLE_POINTS              1064
#define IDC_AUDIO_STOP                  1065
#define IDC_BLOCK_OBSCENITY             1065
#define IDC_READ_Z_BUFFER               1065
#define IDC_STATUS6                     1066
#define IDC_NEBULAE                     1066
#define IDC_PILOT_GUIDE                 1066
#define IDC_STATUS7                     1067
#define IDC_CACHETEXTURES               1067
#define IDC_SPACE_SYSTEM_CHAT_DEFAULT   1067
#define IDC_AUDIO_BUTTON                1068
#define IDC_FULLSCREEN_ANTIALIAS        1068
#define IDC_SECONDARY_CHATSERVER        1068
#define IDC_LIST1                       1069
#define IDC_RICHEDIT1                   1070
#define IDC_LIST2                       1070
#define IDC_WORLD_LIST                  1070
#define IDC_COMBO1                      1071
#define IDC_AUDIO_BUTTON2               1071
#define IDC_BROWSE_BUTTON               1072
#define IDC_COMBO2                      1072
#define IDC_SLIDER1                     1073
#define IDC_COMBO3                      1073
#define IDC_MESSAGE                     1074
#define IDC_COMBO4                      1074
#define IDC_SLIDER2                     1074
#define IDC_AUDIO_FOLDER                1075
#define IDC_COMBO5                      1075
#define IDC_SLIDER3                     1075
#define IDC_GRAPHICSLEVEL_SLIDER        1075
#define IDC_AUDIO_STRING                1076
#define IDC_COMBO6                      1076
#define IDC_SLIDER4                     1076
#define IDC_COMBO7                      1077
#define IDC_SLIDER5                     1077
#define IDC_COMBO8                      1078
#define IDC_SLIDER6                     1078
#define IDC_CURRENT_AUDIO_FOLDER        1079
#define IDC_COMBO9                      1079
#define IDC_ADD_GATEWAY_IP              1080
#define IDC_COMBO10                     1080
#define IDC_BUTTON2                     1081
#define IDC_REFRESH_STATUS              1081
#define IDC_COMBO11                     1081
#define IDC_BANNER                      1082
#define IDC_REMOVE_GATEWAY              1082
#define IDC_COMBO12                     1082
#define IDC_CD_PLAYER                   1083
#define IDC_COMBO13                     1083
#define IDC_TAB1                        1084
#define IDC_UPDATE_WORLDS_LIST          1084
#define IDC_COMBO14                     1084
#define IDC_ISLAND_LIST                 1085
#define IDC_COMBO15                     1085
#define IDC_WORLD_NAME                  1086
#define IDC_COMBO16                     1086
#define IDC_ISLAND_TEXT                 1087
#define IDC_COMBO17                     1087
#define IDC_ISLAND_NAME                 1088
#define IDC_COMBO18                     1088
#define IDC_TEXTURE_DETAIL              1089
#define IDC_COMBO19                     1089
#define IDC_DETAILED_SHADOW             1090
#define IDC_COMBO20                     1090
#define IDC_COMBO21                     1091
#define IDC_ENABLE_SHADOWS              1092
#define IDC_COMBO22                     1092
#define IDC_RESOLUTION_COMBO            1093
#define IDC_UPDATE_SECONDS              1094
#define IDC_DYNAMIC_SHADOW              1095
#define IDC_CONTINUE                    1096
#define IDC_MIPMAP_RESOLUTION           1096
#define IDC_PLAYER_SHADOW_COMBO         1096
#define IDC_BUTTON1                     1097
#define IDC_DRAWDIST                    1097
#define IDC_BUTTON3                     1098
#define IDC_CONNECTING_MESSAGE          1098
#define IDC_RESOLUTION_COMBO2           1098
#define IDC_ENABLE_PLAYER_SHADOWS       1099
#define IDC_BUILDING_SHADOW_COMBO       1099
#define IDC_STATUS_TEXT                 1100
#define IDC_MIPMAP_BIAS                 1100
#define IDC_STATUS_TEXT2                1101
#define IDC_FILTERING                   1101
#define IDC_MAX_SHEEP                   1103
#define ID_CONNECT                      1104
#define IDC_MAX_SHEEP2                  1104
#define IDC_TREE1                       1105
#define IDC_MAX_SHEEP3                  1105
#define ID_ADD_TO_LIST                  1106
#define IDC_COMBO_CONTROL_MODE          1106
#define IDC_EDIT_NEUTRAL_ZONE           1107
#define IDRESET                         1108
#define IDC_COMBO_NEUTRAL_ZONE          1109
#define IDC_LIST_JOY_SETUP              1110
#define IDC_BUTTON_UNSET                1111
#define IDC_CHECK1                      1112
#define IDC_STRING1                     1113
#define IDC_TEXT                        1114
#define IDC_CHECK2                      1115
#define IDC_WASD                        1116
#define IDC_WASD2                       1117
#define IDC_PROGRESS1                   1117
#define IDC_GRAPHICS_LEVEL_DESCRIPTION  1118
#define IDC_WASD3                       1119
#define IDC_RADIOPRESETS_COMBO          1119
#define IDC_WORLD_CONNECT_PROGRESS      1126
#define IDC_CONNECT_STRING              1127
#define IDC_CONNECT_STRING2             1128
#define IDM_VID_OPTIONS                 40001
#define IDM_AUDIO_OPTIONS               40002
#define IDM_SET_TC_ADDRESS              40003
#define IDM_EXIT                        40004
#define IDM_ABOUT                       40005
#define IDM_HOMEPAGE                    40006
#define IDM_KEYBOARD                    40007
#define IDM_KEYBOARD_OPTIONS            40008
#define IDM_QWERTY                      40011
#define IDM_MODELS                      40012
#define IDM_TRACTOR_HOME                40013
#define IDM_CHAT_WINDOW                 40014
#define IDM_GAME_OPTIONS                40015
#define IDM_SHOW_GAME_TIME              40016
#define IDM_SHOW_REAL_TIME              40017
#define ID_VIEW_CHARACTER               40018
#define IDM_BUILDINGS                   40019
#define IDM_TRACTORUNLIMITED            40020
#define IDM_GENERAL_OPTIONS             40021
#define IDM_CHOOSE_FONT                 40022
#define IDM_RETURNTO_FRONT              40023
#define IDK_F7                          40024
#define IDK_F1                          40025
#define IDM_SMALL_ONTOP                 40026
#define ID_OPTIONS_GRAPHICOPTIONS       40027
#define ID_FILE_CHANGENAME              40029
#define IDM_VIEW_ALL_ISLANDS            40031
#define ID_OPTIONS_FULLSCREEN           40032
#define IDM_SMALL_VIDEO                 40033
#define ID_HELP_KEYBOARD                40034
#define IDM_MUSIC                       40035
#define IDM_GATEWAYS_LIST               40036
#define IDM_JOYSTICK_OPTIONS            40037
#define IDM_JOYSTICK                    40038
#define ID_OPTIONS_INVERTMOUSELOCK      40039
#define ID_FILE_ADDGALAXYADDRESSMANUALLY 40040
#define ID_FILE_EXIT                    40041
#define ID_DISPLAY_VERYSMALL            40042
#define ID_FILE_RESETSERVERADDRESSESLIST 40043
#define IDM_CHANGENAME                  40044
#define ID_OPTIONS_AUDIOOPTIONS         40045
#define ID_OPTIONS_SETPROFILE           40046
#define ID_HELP_CHECKFORVERSIONUPDATE   40047
#define ID_HELP_WEBSITE                 40048
#define ID_FILE_REFRESHGATEWAYLIST      40049

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        206
#define _APS_NEXT_COMMAND_VALUE         40050
#define _APS_NEXT_CONTROL_VALUE         1120
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
