//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ModelConverter.rc
//
#define IDC_APPLY                       2
#define ID_APPLY                        3
#define ID_CANCEL                       3
#define IDAPPLY                         3
#define IDD_MODEL_CONVERTER_MAIN        101
#define IDR_MENU1                       102
#define IDD_ABOUT                       103
#define IDD_EXPORT_SETTINGS             104
#define IDD_BATCH_CONVERT               105
#define IDD_BATCH_PROGRESS              106
#define IDD_ANIMATION_BUILDER           107
#define IDR_MENU2                       108
#define IDD_SCALE_DIALOG                109
#define IDD_MOVE_MODEL_DIALOG           109
#define IDD_TURRET_ATTACH_POINT         111
#define IDD_MATERIALS                   112
#define IDB_BITMAP1                     113
#define IDD_SCALE_MODEL_DIALOG          113
#define IDB_BITMAP2                     114
#define IDB_BITMAP3                     115
#define IDB_BITMAP4                     117
#define IDB_BITMAP5                     118
#define IDB_BITMAP6                     119
#define IDB_BITMAP7                     121
#define IDD_LOD_SETTINGS                122
#define IDD_DIALOG1                     123
#define IDD_ABOUTDIALOG                 123
#define IDD_EFFECT_ATTACH               124
#define IDD_ROTATE_DIALOG               125
#define IDD_PRELIGHT_OPTIONS            126
#define IDD_MATERIAL_BROWSER            127
#define IDD_SUBMODEL_BROWSER            128
#define IDD_MATERIAL_ASSIGN             129
#define IDD_UV_UNWRAP                   130
#define IDD_MODEL_TO_SCENE_DIALOG       131
#define IDD_ADDPRIMITIVE                132
#define IDD_DIALOG2                     133
#define IDD_BATCH_RESCALE               133
#define IDD_CURVED_WALL                 134
#define IDC_LIST1                       1000
#define IDC_PROGRESS1                   1000
#define IDC_EXPORT_SETTINGS             1003
#define IDC_CHECK1                      1004
#define IDC_CHECK2                      1005
#define IDC_TAB1                        1005
#define IDC_GLOBAL_CHECK                1005
#define IDC_CHECK3                      1006
#define IDC_EDIT1                       1006
#define IDC_SHOW_COLLISION              1006
#define IDC_CHECK4                      1007
#define IDC_BUTTON1                     1007
#define IDC_EDIT2                       1007
#define IDC_CHECK5                      1008
#define IDC_BUILDING_SCALE_CHECK        1008
#define IDC_BUTTON2                     1008
#define IDC_EDIT3                       1008
#define IDC_CHECK6                      1009
#define IDC_CONVERTING                  1009
#define IDC_REMOVE_KEYFRAME             1009
#define IDC_STICK_TO_FLOOR              1009
#define IDC_EDIT4                       1009
#define IDC_SUBMODEL_EXPORT             1009
#define IDC_COMBO1                      1010
#define IDC_EDIT5                       1010
#define IDC_CHECK13                     1010
#define IDC_ANIMATION_USE_LIST          1011
#define IDC_COMBO2                      1011
#define IDC_EDIT6                       1011
#define IDC_CHECK10                     1011
#define IDC_KEYSTRING1                  1012
#define IDC_EDIT7                       1012
#define IDC_CHECK11                     1012
#define IDC_KEYSTRING2                  1013
#define IDC_EDIT8                       1013
#define IDC_CHECK12                     1013
#define IDC_KEYSTRING3                  1014
#define IDC_EDIT9                       1014
#define IDC_CHECK14                     1014
#define IDC_KEYFRAME1                   1015
#define IDC_EDIT10                      1015
#define IDC_BUTTON5                     1015
#define IDC_SELECT_MAPPED_FACES         1015
#define IDC_KEYFRAME_TIME               1016
#define IDC_KEYFRAME_TIME_EDIT          1016
#define IDC_EDIT11                      1016
#define IDC_SLIDER1                     1017
#define IDC_CHECK7                      1017
#define IDC_HORIZTURRET_ROT             1017
#define IDC_CURRENT_SCALE               1018
#define IDC_BUTTON6                     1018
#define IDC_EDIT29                      1018
#define IDC_VERTTURRET_ROT              1018
#define IDC_SPIN1                       1019
#define IDC_EDIT12                      1019
#define IDC_CURRENT_Y_SCALE             1019
#define IDC_CHECK8                      1020
#define IDC_CURRENT_X_SCALE             1020
#define IDC_LOCAL_LOCK                  1021
#define IDC_BUTTON7                     1021
#define IDC_CURRENT_Z_SCALE             1021
#define IDC_REGISTERED_LOCK             1022
#define IDC_EDIT13                      1022
#define IDC_ID_LOCK                     1023
#define IDC_CHECK9                      1023
#define IDC_NO_LOCK                     1024
#define IDC_EDIT14                      1024
#define IDC_LOCK_ID_STRING              1025
#define IDC_EDIT15                      1025
#define IDC_BLENDTYPE_COMBO             1026
#define IDC_EDIT16                      1026
#define IDC_DOUBLE_SIDED_CHECK          1027
#define IDC_EDIT17                      1027
#define IDC_SINGLE_SPRITE_CHECK         1028
#define IDC_EDIT18                      1028
#define IDC_MOVE_BUT                    1029
#define IDC_POLYGON_SPRITES_CHECK       1029
#define IDC_EDIT19                      1029
#define IDC_DONT_CLAMP_UVS              1029
#define IDC_ROT_BUT                     1030
#define IDC_FILTERING                   1030
#define IDC_EDIT20                      1030
#define IDC_ZOOM_BUT                    1031
#define IDC_LIGHTING                    1031
#define IDC_EDIT21                      1031
#define IDC_CENTRE_BUT                  1032
#define IDC_COLLISION_CHECK             1032
#define IDC_EDIT22                      1032
#define IDC_BUTTON3                     1033
#define IDC_LARGE_MODEL_CLIPPING        1033
#define IDC_EDIT23                      1033
#define IDC_REFRESH_TEXTURE             1034
#define IDC_BUTTON4                     1034
#define IDC_EDIT24                      1034
#define IDC_NO_SHADOWS                  1034
#define IDC_RADIO1                      1035
#define IDC_EDIT25                      1035
#define IDC_NO_SHADOWS2                 1035
#define IDC_RESET_CAM_TO_MODEL          1035
#define IDC_RADIO2                      1036
#define IDC_EDIT26                      1036
#define IDC_RESET_CAM_TO_SCENE          1036
#define IDC_MIPBIAS                     1036
#define IDC_X_TEXT                      1037
#define IDC_RADIO3                      1037
#define IDC_EDIT27                      1037
#define IDC_Y_TEXT                      1038
#define IDC_EDIT28                      1038
#define IDC_RADIO_ALL_LODS              1038
#define IDC_Z_TEXT                      1039
#define IDC_CHECK15                     1039
#define IDC_RADIO_APPLY_TO_HIGH_LOD     1039
#define IDC_COMBO_LOD                   1040
#define IDC_CHECK16                     1040
#define IDC_LODUSED_TEXT                1041
#define IDC_CHECK17                     1041
#define IDC_COMBO_LOD2                  1042
#define IDC_DISPLAY_TEXT2               1042
#define IDC_BUTTON9                     1042
#define IDC_LAND_SCALE                  1043
#define IDC_BUTTON10                    1043
#define IDC_BOUNCINESS                  1044
#define IDC_BUTTON11                    1044
#define IDC_EXTRACT_SPECULAR_TEX        1045
#define IDC_BLENDTYPE_COMBO2            1046
#define IDC_CHANGE_DIFFUSE              1047
#define IDC_CHANGE_DIFFUSE2             1048
#define IDC_MODEL_DETAILS_TEXT          1049
#define IDC_EXTRACT_DIFFUSE_TEX         1049
#define IDC_CHANGE_DIFFUSE3             1050
#define IDC_EXTRACT_NORMAL_TEX          1050
#define IDC_REMOVE_DIFFUSE_TEXTURE      1051
#define IDC_REMOVE_SUBMODEL             1052
#define IDC_EXTRACT_EMISSIVE_TEX        1052
#define IDC_REMOVE_DIFFUSE_TEXTURE2     1053
#define IDC_REMOVE_SPECULAR_TEXTURE     1053
#define IDC_CONTROL_CAMERA              1054
#define IDC_REMOVE_DIFFUSE_TEXTURE3     1055
#define IDC_REMOVE_NORMAL_TEXTURE       1055
#define IDC_CONTROL_PICKER              1056
#define IDC_SUBMODEL_CHANGE             1057
#define IDC_CONTROL_PICKER2             1057
#define IDC_CONTROL_VERTEXPICKER        1058
#define IDC_SELECTION_GROUP             1059
#define IDC_FOCUS_SELECTION             1060
#define IDC_CONTROL_PICKER4             1061
#define IDC_CONTROL_POLYSLICE           1061
#define IDC_ASSIGN_MATERIAL             1062
#define IDC_ADDNEWMATERIAL              1063
#define IDC_ASSIGN_MATERIAL2            1063
#define IDC_SLICE_FACES                 1063
#define IDC_SELECTION_GROUP2            1064
#define IDC_MOVE_VERTS                  1064
#define IDC_FOCUS_MODEL                 1065
#define IDC_UVUNWRAP                    1066
#define IDC_DISPLAY_FRAME               1067
#define IDC_ROTATE_VERTS                1067
#define IDC_RESETVIEW                   1068
#define IDC_SCALE_VERTS                 1068
#define IDC_SUBDIVIDE                   1069
#define IDC_ANIM_STOP                   1070
#define IDC_ANIM_PLAY                   1071
#define ID_UV_CANCEL                    1072
#define IDC_AXIS_SNAP                   1072
#define IDC_SUBDIVIDE2                  1073
#define IDC_RESET_PLANE                 1073
#define IDC_SCALE_UNITS                 1074
#define IDC_FOCUS_SELECTION2            1075
#define IDC_BUTTON8                     1076
#define IDC_FOCUS_MODEL2                1077
#define IDC_POSLABELX                   1078
#define IDC_POSLABELY                   1079
#define IDC_POSLABELZ                   1080
#define IDC_POSVALUEX                   1081
#define IDC_POSVALUEY                   1082
#define IDC_POSVALUEZ                   1083
#define IDC_EFFECT_TYPE_COMBO           1084
#define IDC_MAINLODCOMBO                1085
#define IDC_SELECTIONTEXT               1086
#define IDC_VIEWLODTEXT                 1087
#define IDC_ANIMTEXT                    1088
#define IDC_SELECTIONTEXT2              1089
#define IDC_SELECTIONTEXT3              1090
#define IDC_DELETE_FACES                1091
#define IDC_DIFFUSE_EMBED               1092
#define IDC_LEFT_TEXTBOX                1092
#define IDC_RIGHT_TEXTBOX               1093
#define IDC_VIEWLODTEXT2                1093
#define IDC_SELECT_CONNECTED            1094
#define IDC_PROGRESS2                   1095
#define IDC_VIEWLODTEXT3                1095
#define IDC_MAIN_PROGRESS               1096
#define IDC_LOCKX                       1097
#define IDC_LOCKY                       1098
#define IDC_LOCKTEXT                    1099
#define IDC_LOCKZ                       1100
#define IDC_OUTPUT_LIST                 1101
#define IDC_NUMVERTSX                   1102
#define IDC_NUMVERTSX2                  1103
#define IDC_NUMVERTSY                   1103
#define IDC_WALL_DEPTH                  1103
#define IDC_NUMVERTSX3                  1104
#define IDC_NUMVERTSZ                   1104
#define IDC_SELECT_VERTS                1105
#define IDC_WALL_HEIGHT                 1105
#define IDC_SCALE_FACTOR                1106
#define IDC_NUM_DIVISIONS               1106
#define IDC_BATCH_FOLDER                1107
#define IDC_PROGRESS_TEXT               1108
#define IDC_INNER_RADIUS                1109
#define IDC_ATTACHLABELZ                1110
#define IDC_ATTACHLABELY                1111
#define IDC_ATTACHLABELX                1112
#define IDC_OFFSETX                     1113
#define IDC_OFFSETY                     1114
#define IDC_OFFSETZ                     1115
#define IDC_OFFSETCHECK                 1116
#define IDM_FILE_EXIT                   40001
#define ID_FILE_IMPORT                  40002
#define ID_FILE_SAVEAS                  40004
#define ID_HELP_PANIC                   40006
#define IDM_FIX_BUILDING_SCALE          40007
#define IDM_SELECT_TEXTURE              40008
#define ID_RENDERING_GOURAUDSHADING     40009
#define ID_OPTIONS_EXPORTSETTINGS       40010
#define ID_TOOLS_JOINVERTICES           40011
#define ID_TOOLS_COMPRESSVERTICES       40012
#define ID_TOOLS_COMPRESSNORMALS        40013
#define ID_TOOLS_EDITBUILDERINFO        40014
#define IDM_FILE_OPEN                   40015
#define ID_TOOLS_STICKTOFLOORVEHICLES   40016
#define ID_TOOLS_STICKTOFLOOR           40016
#define ID_RENDERING_CULLING_NONE       40017
#define ID_RENDERING_CULLING_NORMAL     40018
#define ID_RENDERING_CULLING_REVERSE    40019
#define ID_TOOLS_CENTREHORIZONTALLY     40020
#define ID_FILE_BATCHCONVERT            40021
#define ID_EXPORTOPTIONS_COMPRESSTEXTURECOORDS 40022
#define ID_EXPORTOPTIONS_EXPORTVERTEXCOLOURS 40023
#define ID_EXPORTOPTIONS_SHAREDNORMALS  40024
#define ID_EXPORTOPTIONS_MATERIALS      40025
#define ID_HELP_ABOUT                   40026
#define ID_ANIMATIONS_BUILDANIMATIONS   40027
#define ID_ANIMATIONS_BLENDING_NONE     40028
#define ID_ANIMATIONS_BLENDING_LINEAR   40029
#define ID_ANIMATIONS_BLENDING_SLERP    40030
#define ID_EXPORTOPTIONS_EXPORTNORMALSFORLIGHTING 40032
#define ID_ANIMATIONS_ADDPLANETURRET    40033
#define ID_ANIMATIONS_ADDHORIZTURRET    40033
#define ID_ANIMATIONS_ADDVERTICALTURRET 40034
#define ID_FILE_NEWANIMATION            40035
#define ID_FILE_EXITANIMATIONBUILDER    40036
#define IDM_FILE_NEW                    40038
#define ID_TOOLS_TURNINSIDEOUT          40039
#define ID_TOOLS_SCALETOTRACTORSIZE     40040
#define ID_TOOLS_SETFRONT               40041
#define ID_TOOLS_ROTATE                 40041
#define ID_TOOLS_SETTOP                 40042
#define ID_TOOLS_FIXBUILDINGSCALE       40047
#define ID_ANIMATIONS_SETHORIZONTALTURRETATTACHPOINT 40048
#define ID_EXPORTOPTIONS_EXPORTANIMATEDNORMALS 40049
#define ID_TOOLS_REVERSENORMALS         40051
#define ID_ANIMATIONS_SETVERTICALTURRETATTACHPOINT 40052
#define ID_SPECIAL_SETGUNFIREATTACHVERTEX 40053
#define ID_SPECIAL_SETCAMERAATTACHPOINT 40054
#define ID_SPECIAL_SETEFFECTATTACHPOINT 40054
#define IDM_FLIP_FACES                  40055
#define ID_SPECIAL_SETCARRIEDOBJECTATTACHPOINT 40056
#define ID_SPECIAL_MATERIALPROPERTIES   40057
#define ID_TOOLS_SCALETOTILESIZEX       40058
#define ID_TOOLS_SCALETOTILESIZEY       40059
#define ID_FILE_EXPORT                  40060
#define ID_ANIMATIONS_ADDWHEELMODEL1    40061
#define ID_ANIMATIONS_ADDWHEELMODEL2    40062
#define ID_ANIMATIONS_SETWHEELATTACHPOINT1 40063
#define ID_ANIMATIONS_SETWHEELATTACHPOINT2 40064
#define ID_ANIMATIONS_SETWHEELATTACHPOINT3 40067
#define ID_ANIMATIONS_SETWHEELATTACHPOINT4 40068
#define ID_LEVELOFDETAIL_ADDMEDLODMODEL 40069
#define ID_LEVELOFDETAIL_ADDLOWLODMODEL 40070
#define IDM_ADD_COLLISION_MODEL         40071
#define IDM_FILE_SAVE                   40072
#define IDM_MOVE                        40073
#define IDM_LOD_SETTINGS                40074
#define ID_FILE_BATCHPROCESS_CONVERTMODELS 40075
#define ID_FILE_BATCHPROCESS_SCALEMODELS 40076
#define IDM_WHEEL_PROPS                 40077
#define IDM_ATM_COMPRESSION             40078
#define IDM_DRAW_GRID_LINES             40079
#define ID_RENDERING_BACKGROUNDCOLOUR_GREY 40081
#define ID_RENDERING_BACKGROUNDCOLOUR_GREEN 40082
#define ID_RENDERING_BACKGROUNDCOLOUR_BLACK 40083
#define ID_RENDERING_BACKGROUNDCOLOUR_WHITE 40084
#define ID_RENDERING_BACKGROUNDCOLOUR_BLUE 40085
#define ID_RENDERING_BACKGROUNDCOLOUR_RED 40086
#define ID_EXPORTOPTIONS_EFFECTS        40087
#define ID_TOOLS_ROTATEFREE             40088
#define ID_HELP_HELPMANUAL              40089
#define ID_TOOLS_RESETVERTEXCOLOURS     40090
#define ID_TOOLS_PRELIGHT               40091
#define ID_MATERIALS_MATERIALBROWSER    40092
#define ID_SUBMODELS_VIEWEDITSUBMODELS  40093
#define ID_RENDERING_MODELDISPLAY_NORMAL 40094
#define ID_RENDERING_MODELDISPLAY_POLYEDGES 40095
#define ID_RENDERING_MODELDISPLAY_SHOWVERTICES 40096
#define ID_LEVELOFDETAIL_DISPLAY_DEPENDONVIEW 40098
#define ID_LEVELOFDETAIL_DISPLAY_HIGH   40099
#define ID_LEVELOFDETAIL_DISPLAY_MEDLODALWAYS 40100
#define ID_LEVELOFDETAIL_DISPLAY_LOWLODALWAYS 40101
#define ID_SUBMODELS_WHEELMODE_NORMAL   40102
#define ID_SUBMODELS_WHEELMODE_PLANETYPE1 40103
#define ID_SUBMODELS_WHEELMODE_PLANETYPE2 40104
#define ID_SUBMODELS_WHEELMODE_HELICOPTER 40105
#define ID_SUBMODELS_WHEELMODE_HELICOPTER4 40106
#define ID_SUBMODELS_WHEELMODE_BIKE     40107
#define ID_MATERIALS_ADDMATERIALS       40108
#define ID_RENDERING_ASPECTRATIO_VARIABLE 40109
#define ID_RENDERING_ASPECTRATIO_169    40110
#define ID_RENDERING_ASPECTRATIO_43FIXED 40111
#define ID_RENDERING_ASPECTRATIO_1610FIXED 40112
#define ID_RENDERING_CLEAROVERRIDETEXTURE 40113
#define ID_SELECTION_SELECTALL          40114
#define ID_SELECTION_SELECTBYMATERIAL_NOMATERIALS 40115
#define ID_RENDERING_MENUOPTIONS_SCALEMODE_101M 40117
#define ID_RENDERING_MENUOPTIONS_SCALEMODE_10100FTTHEUNIVERSALMODE 40118
#define ID_SCENETOOLS_CREATENEWSCENE    40119
#define ID_SCENETOOLS_CREATESCENEFROMMODEL 40120
#define ID_SCENETOOLS_EXPORTSCENEFILE   40121
#define ID_RENDERING_LIGHTING_EDITORSTANDARD 40123
#define ID_RENDERING_LIGHTING_SPACE     40124
#define ID_RENDERING_LIGHTING_SUNSET    40125
#define ID_SUBMODELS_LEVELOFDETAIL_EXTRACTLODS 40126
#define ID_TOOLS_FIXNORMALS             40127
#define ID_TOOLS_CONVERTYUPTOZUP        40128
#define ID_TOOLS_RECALCNORMALS_STANDARDFACEORIENTATION 40129
#define ID_TOOLS_RECALCNORMALS_ALLNORMALSUP 40130
#define ID_MATERIALS_DELETEALLMATERIALS 40131
#define ID_SELECTION_INVERTSELECTION    40132
#define ID_SELECTION_SELECTALLWITHSAMEMATERIAL 40133
#define ID_SELECTION_SELECTALLCONNECTED 40134
#define ID_RENDERING_SHOWNORMALS        40135
#define ID_RECALCNORMALS_STANDARDMODE2  40136
#define ID_LIGHTING_WHITEABOVE          40137
#define ID_LIGHTING_WHITEBELOW          40138
#define ID_FILE_SAVESELECTIONAS         40139
#define ID_TOOLS_SEPARATEVERTS          40141
#define ID_MATERIALS_COMBINEINTOSINGLEMATERIAL 40142
#define ID_TOOLS_DELETEISOLATEDVERTICES 40143
#define ID_SCENETOOLS_ADDPRIMITIVE      40144
#define ID_ADDPRIMITIVE_CUBOID          40145
#define ID_ADDPRIMITIVE_SPHERE          40146
#define ID_ADDPRIMITIVE_CONE            40147
#define ID_ADDPRIMITIVE_PYRAMID         40148
#define ID_UVSMATERIALS_UVGENERATE      40149
#define ID_UVGENERATE_BOX               40150
#define ID_SHADOWS_NONE                 40151
#define ID_SHADOWS_SHADOW_MAP           40152
#define ID_SHADOWS_SHADOW_VOLUME        40153
#define ID_SUBMODELS_WHEELMODE_WHEELS_YFORWARD 40154
#define ID_SUBMODELS_WHEELMODE_BIKE_YFORWARD 40155
#define ID_SUBMODELS_WHEELMODE_PLANETYPE1_YFORWARD 40156
#define ID_SUBMODELS_WHEELMODE_PLANETYPE2_YFORWARD 40157
#define ID_SCALE_SCALEDIALOG            40158
#define ID_SCALE_SCALEUPOLDTUMODEL      40159
#define ID_SCENETOOLS_ADDPRIMITIVE_WALLCIRCLE 40160
#define ID_IMPORTUVS                    40161
#define ID_SCALE_SCALETO15GRID          40162
#define ID_REMOVEALLANIMATIONS          40163
#define ID_EXPORT_THUMBNAIL             40164
#define ID_SUBMODELS_WHEELMODE_WHEELS_YFORWARD_NOSTEER 40165
#define IDM_SCALE_MATCH                 40166
#define IDM_FIX_OLD_VEHICLE             40167
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        135
#define _APS_NEXT_COMMAND_VALUE         40168
#define _APS_NEXT_CONTROL_VALUE         1117
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
